update remove and add book
Bigizi/BookStore-React pull request #3
Opened 2023-03-07 21:24 UTC by Bigizi

**Store Book React Project**

I connected the configureStore file to the main component of your React app.
I added a slice that contains my books
I displayed books, received from the slice, in a reusable component
I add an event handler to add and remove buttons

2023-03-07 21:44 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @Bigizi, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 21:44 UTC, anagudelogu commented on src/components/Book.js
> +  const book = useSelector((state) => state.books);
- [ ] Please don't forget to remove old pieces of commented code, they make your code base look ugly and make it less readable. 🤓 🔧

2023-03-07 21:44 UTC, anagudelogu commented on src/components/Book.js
> +            {/* <button type="button">Edit</button> */}
- [ ] Please don't forget to remove old pieces of commented code, they make your code base look ugly and make it less readable. 🤓 🔧

2023-03-07 21:44 UTC, anagudelogu commented on src/components/Book.js
> +    console.log(bookId);
- [ ] According to the [JavaScript best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md):

![image](https://user-images.githubusercontent.com/77069011/223558249-5b5bdf97-79ae-44bb-9921-d5313f6317cf.png)

Please consider removing this `console.log()` statement! 🤓 🔧

2023-03-07 21:44 UTC, anagudelogu commented on src/components/routes/Books.js
> +// import { v4 as uuidv4 } from 'uuid';
- [ ] Please don't forget to remove old pieces of commented code, they make your code base look ugly and make it less readable. 🤓 🔧

2023-03-07 21:44 UTC, anagudelogu commented on src/components/routes/Categories.js
> +  // };
- [ ] Please don't forget to remove old pieces of commented code, they make your code base look ugly and make it less readable. 🤓 🔧

2023-03-08 08:12 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @Bigizi, 

To highlight 👍🏽 
✔️ README is professional
✔️ Codebase is clean
✔️ No errors

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/749155b89333c6d89386f5c98dd110e234a00f2aa1e864a5b3fecaf089aedb27/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f36664a31424d375232454252446e784b2f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-03-08 13:15 UTC, merged